// Code generated by "stringer -type=Type"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LEFT_PAREN-0]
	_ = x[RIGHT_PAREN-1]
	_ = x[MINUS-2]
	_ = x[PLUS-3]
	_ = x[SLASH-4]
	_ = x[STAR-5]
	_ = x[BANG-6]
	_ = x[BANG_EQUAL-7]
	_ = x[EQUAL-8]
	_ = x[EQUAL_EQUAL-9]
	_ = x[GREATER-10]
	_ = x[GREATER_EQUAL-11]
	_ = x[LESS-12]
	_ = x[LESS_EQUAL-13]
	_ = x[IDENTIFIER-14]
	_ = x[NUMBER-15]
	_ = x[EOF-16]
}

const _Type_name = "LEFT_PARENRIGHT_PARENMINUSPLUSSLASHSTARBANGBANG_EQUALEQUALEQUAL_EQUALGREATERGREATER_EQUALLESSLESS_EQUALIDENTIFIERNUMBEREOF"

var _Type_index = [...]uint8{0, 10, 21, 26, 30, 35, 39, 43, 53, 58, 69, 76, 89, 93, 103, 113, 119, 122}

func (i Type) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Type_index)-1 {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[idx]:_Type_index[idx+1]]
}
